import { Button, Modal } from "@mantine/core";

import Flow from "components/Flow";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [opened, setOpened] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <Button onClick={() => setOpened(true)}>Send money</Button>
        <span>Blockchain Simulator</span>
      </header>
      <Flow />
      <Modal
        opened={opened}
        onClose={() => setOpened(false)}
        title="Send money"
      >
        {/* Modal content */}
      </Modal>
    </div>
  );
};

export default Home;
