import Node from "components/node";
import type { NextPage } from "next";
import Head from "next/head";
import { Fragment } from "react";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <Fragment>
      <div className={styles.container}>
        <Head>
          <title>Blockchain Visualization</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className={styles.header}>
          <span>Blockchain Visualization</span>
        </header>
        <Node />
      </div>
    </Fragment>
  );
};

export default Home;
